In [1]:
import numpy as np

In [13]:
a=np.zeros(3).reshape((1,3))

In [17]:
a=[[1, 3 , 4]]

In [18]:
print(a)

[[1, 3, 4]]


In [20]:
b=[[1, 3 , 4]]

In [28]:
print(a,b)

([[1, 3, 4]], [[1, 3, 4]])


In [30]:
len(a)

1

In [33]:
b=np.arange(20).reshape((5,4))

In [34]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [36]:
print(len(b))

5


In [38]:
x=b

In [39]:
sum(len(x) for x in input)

TypeError: 'function' object is not iterable