In [47]:
import numpy as np

In [50]:
a=range(2,6)

In [52]:
print(a)

[2, 3, 4, 5]


In [58]:
a=np.arange(72).reshape((2,3,4,3))

In [59]:
print(a)

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]
   [18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]
   [30 31 32]
   [33 34 35]]]


 [[[36 37 38]
   [39 40 41]
   [42 43 44]
   [45 46 47]]

  [[48 49 50]
   [51 52 53]
   [54 55 56]
   [57 58 59]]

  [[60 61 62]
   [63 64 65]
   [66 67 68]
   [69 70 71]]]]


In [61]:
print(a[0,0])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [63]:
print(range(5))

[0, 1, 2, 3, 4]


In [65]:
print(range(0,5))

[0, 1, 2, 3, 4]


In [70]:
np.unravel_index(3,(3,3))

(1, 0)

In [72]:
1/2


0

In [75]:
1//2


0

In [78]:
10/3


3