In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape((3,4))

In [3]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
b=2*a
print(b)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [7]:
b=b+1

In [9]:
print(b)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [10]:
print(a/b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
c=np.divide(a,b)
c=np.true_divide(a,b)
d=np.arange(3).reshape((3,1))+1
e=np.true_divide(a,d)
print(a)
print(d)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1]
 [2]
 [3]]
[[0.         1.         2.         3.        ]
 [2.         2.5        3.         3.5       ]
 [2.66666667 3.         3.33333333 3.66666667]]


In [32]:
print(a[:,1])
print(a[d-1,:])
print(a[:,d-1])

[1 5 9]
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
[[[ 0]
  [ 1]
  [ 2]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 8]
  [ 9]
  [10]]]


In [22]:
print(c)

[[0.         0.25       0.33333333 0.375     ]
 [0.4        0.41666667 0.42857143 0.4375    ]
 [0.44444444 0.45       0.45454545 0.45833333]]


In [24]:
print(b*c)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [27]:
print(a[d-1,d])

[[ 1]
 [ 6]
 [11]]
