In [6]:
import numpy as np
x=np.arange(12).reshape((3,4))
y=np.arange(12).reshape((4,3))

In [7]:
print(x*y)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [10]:
k=(x.dot(y))

In [13]:
z=np.invert(k)
print(z*k)
print(z.dot(k))
print(k.dot(z))

[[ -1806  -2352  -2970]
 [-13110 -18632 -25122]
 [-34782 -50400 -68906]]
[[ -17622  -21048  -24474]
 [ -50022  -59768  -69514]
 [ -82422  -98488 -114554]]
[[ -17424  -20784  -24144]
 [ -50088  -59768  -69448]
 [ -82752  -98752 -114752]]
